app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:     /

# sonata admin

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin


_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# fos_user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media