sonata_media:
    # if you don't use default namespace configuration
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: Application\Sonata\ClassificationBundle\Entity\Category
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            download:
                mode: http # X-Sendfile | http
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100, height: 100, quality: 100}
                preview: { width: 800, height: 800, quality: 100}

        article:
            providers:
              - sonata.media.provider.image
              - sonata.media.provider.file

            formats:
                image_feature : { width: 180, height: 180, quality: 100}
                image_content: { width: 400, height: 400, quality: 100}
        product:
            providers:
              - sonata.media.provider.image
            formats:
                image_feature : { width: 180, height: 180, quality: 100}
                image_content: { width: 400, height: 400, quality: 100}
        category:
            providers:
              - sonata.media.provider.image
            formats:
                preview: { width: 800, height: 800, quality: 10}
        slider:
            providers:
              - sonata.media.provider.image
            formats:
                preview: { width: 1250, height: 800, quality: 100}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false


doctrine:
    orm:
        entity_managers:
            default:
                mappings:
#                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~

