app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }


app_category:
    path:   /{slug}
    defaults: { _controller: AppBundle:Category:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"
app_product_detail:
    path:   /danh-muc-san-pham/{slug}
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"

app_product_card:
    path:   /gio-hang/them-hang
    defaults: { _controller: AppBundle:Card:index }



app_list_new:
    path:  /cam-nang-lam-dep/tin-tuc
    defaults: { _controller: AppBundle:New:index }

app_contact:
    path:  /lien-he/thong-tin/thong-tin-len-he
    defaults: { _controller: AppBundle:Contact:index }
