app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app_list_product_trademark:
        path:   /san-pham/thuong-hieu
        defaults: { _controller: AppBundle:Category:index}

app_list_new:
    path:  /cam-nang-lam-dep/tin-tuc
    defaults: { _controller: AppBundle:New:index }

app_list_new_detail:
    path:  /cam-nang-lam-dep/{alias}
    defaults: { _controller: AppBundle:New:detail }
    requirements:
        alias: "[a-zA-Z0-9\-_–]+"

app_list_product_hot :
        path:   /san-pham-ban-chay
        defaults: { _controller: AppBundle:Product:index }
app_product_card_edit:
    path:   /gio-hang/chi-tiet/sua-don-hang
    defaults: { _controller: AppBundle:Card:edit }

app_block_search :
     path:  /render/block/search/12/19/2016
     defaults: { _controller: AppBundle:Base:search }

app_block_menu :
     path:  /render/block/menu/12/19/2016
     defaults: { _controller: AppBundle:Base:menu }

#block
app_block_slider :
     path:  /render/block/slider/12/19/2016
     defaults: { _controller: AppBundle:Base:slider }

app_block_news :
     path:  /render/block/news/12/19/2016
     defaults: { _controller: AppBundle:Base:news }

app_block_banner :
     path:  /render/block/banner/12/19/2016
     defaults: { _controller: AppBundle:Base:banner }
app_block_footer :
     path:  /render/block/footer/12/19/2016
     defaults: { _controller: AppBundle:Base:footer }
#endblock
#category
app_category:
    path:   /danh-muc/{alias}
    defaults: { _controller: AppBundle:Category:index }
    requirements:
        alias: "[a-zA-Z0-9\-_–]+"
#endcategory
#product
app_product_detail:
    path:   /chi-tiet-san-pham/{slug}
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"

app_product_detail_2:
    path:   /{category}/{slug}
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"
        category: "[a-zA-Z0-9\-_–]+"

app_product_card:
    path:   /gio-hang/chi-tiet/{slug}
    defaults: { _controller: AppBundle:Card:index }
    requirements:
        slug: "dat-hang"

#endproduct

app_contact:
    path:  /lien-he/thong-tin/thong-tin-len-he
    defaults: { _controller: AppBundle:Contact:index }

app_form_search :
     path:  /tim-kiem
     defaults: { _controller: AppBundle:Product:search }

app_card_submit_card :
     path:  /gio-hang/chi-tiet/dat-hang/{url}
     defaults: { _controller: AppBundle:Card:submit }
     requirements:
        url: "thanh-toan"

#ajax

app_block_ajax_city :
     path:  /_ajax/get_data/load_city
     defaults: { _controller: AppBundle:Ajax:loadCity }
