app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }


app_category:
    path:   /danh-muc/{slug}
    defaults: { _controller: AppBundle:Category:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"
app_product_detail:
    path:   /danh-muc-san-pham/{slug}
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"

app_product_card:
    path:   /gio-hang/them-hang
    defaults: { _controller: AppBundle:Card:index }

app_list_product_hot :
        path:   /san-pham-ban-chay
        defaults: { _controller: AppBundle:Product:index }

app_list_product_trademark:
        path:   /san-pham/thuong-hieu
        defaults: { _controller: AppBundle:Category:index}

app_list_new:
    path:  /cam-nang-lam-dep/tin-tuc
    defaults: { _controller: AppBundle:New:index }

app_contact:
    path:  /lien-he/thong-tin/thong-tin-len-he
    defaults: { _controller: AppBundle:Contact:index }

app_form_search :
     path:  /tim-kiem
     defaults: { _controller: AppBundle:Product:search }


app_block_search :
     path:  /render/block/search
     defaults: { _controller: AppBundle:Base:search }

app_block_menu :
     path:  /render/block/menu
     defaults: { _controller: AppBundle:Base:menu }