app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }


app_category:
    path:   /danh-muc/{alias}
    defaults: { _controller: AppBundle:Category:index }
    requirements:
        alias: "[a-zA-Z0-9\-_–]+"
app_product_detail:
    path:   /chi-tiet-san-pham/{slug}
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        slug: "[a-zA-Z0-9\-_–]+"

app_product_card:
    path:   /gio-hang/chi-tiet
    defaults: { _controller: AppBundle:Card:index }
app_product_card_edit:
    path:   /gio-hang/chi-tiet/sua-don-hang
    defaults: { _controller: AppBundle:Card:edit }

app_list_product_hot :
        path:   /san-pham-ban-chay
        defaults: { _controller: AppBundle:Product:index }

app_list_product_trademark:
        path:   /san-pham/thuong-hieu
        defaults: { _controller: AppBundle:Category:index}

app_list_new:
    path:  /cam-nang-lam-dep/tin-tuc
    defaults: { _controller: AppBundle:New:index }

app_list_new_detail:
    path:  /cam-nang-lam-dep/{alias}
    defaults: { _controller: AppBundle:New:detail }
    requirements:
        alias: "[a-zA-Z0-9\-_–]+"

app_contact:
    path:  /lien-he/thong-tin/thong-tin-len-he
    defaults: { _controller: AppBundle:Contact:index }

app_form_search :
     path:  /tim-kiem
     defaults: { _controller: AppBundle:Product:search }


app_block_search :
     path:  /render/block/search
     defaults: { _controller: AppBundle:Base:search }

app_block_menu :
     path:  /render/block/menu
     defaults: { _controller: AppBundle:Base:menu }

app_block_slider :
     path:  /render/block/slider
     defaults: { _controller: AppBundle:Base:slider }

app_block_news :
     path:  /render/block/news
     defaults: { _controller: AppBundle:Base:news }

app_card_submit_card :
     path:  /gio-hang/chi-tiet/dat-hang
     defaults: { _controller: AppBundle:Card:submit }


#ajax

app_block_ajax_city :
     path:  /_ajax/get_data/load_city
     defaults: { _controller: AppBundle:Ajax:loadCity }
