# src/AppBundle/Resources/config/services.yml
services:
    jobz_user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jobz_user_registration }

    base_controller:
         class:  AppBundle\Controller\BaseController
         calls:
             - [setContainer, ["@service_container"]]
         arguments: ["@doctrine.orm.entity_manager"]

#
##   Extension twig
#    app.service.twig_extension:
#            class: AppBundle\Twig\Extension
#            public: false
#            arguments:
#                - @service_container
#                - @translator
#            tags:
#                - { name: twig.extension }
##Custom resize image
#    sonata.media.resizer.custom:
#        class: AppBundle\Resizer\CustomResizer
#        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]

#        #Create Extension
#    cmn.admin.create.extension:
#        class: AppBundle\Extensions\Util
#       #Custom provider